config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get 'playlist-total', to: "pages#playlist_total", as: :playlist_total
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/yt_playlist.rb
class YtPlaylist
  include ActiveModel::Model
  include ActiveModel::Validations
  include ActionView::Helpers::TextHelper
  
  attr_accessor :url
  
  attr_reader :title
  attr_reader :videos
  attr_reader :total_duration
  
  validates_url :url, message: "Please enter a valid url"
  
  def process_playlist
    begin
      Yt.configuration.api_key = Rails.application.secrets.youtube_api_key
      query_hash = Rack::Utils.parse_query URI(self.url).query
      if query_hash['list'].nil?
        errors.add(:url, "Not a valid playlist url")
        return false
      end
      
      playlist = Yt::Playlist.new(id: query_hash['list'])
      @title = playlist.title
      total_duration = Time.at(0)
      @videos = []
      playlist.playlist_items.each do |item|
        begin
          video = Yt::Video.new(id: item.video_id)
          @videos << { id: video.id, title: video.title, length: video.length,
                       thumbnail_url: video.thumbnail_url }
        rescue
          next  # for deleted and invalid videos
        end
        total_duration += video.duration
      end
      
      if total_duration.day > 1
        @total_duration = "#{pluralize(total_duration.day - 1 , "day")} and "
        @total_duration += total_duration.strftime("%H:%M:%S")
      else
        @total_duration = total_duration.strftime("%H:%M:%S")
      end
    rescue
      errors.add(:url, "Error retrieving playlist data")
      return false
    end
    
    return true
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @playlist = YtPlaylist.new
  end
  
  def playlist_total
    @playlist = YtPlaylist.new(yt_playlist_params)
    if @playlist.valid? && @playlist.process_playlist
      render :playlist_total  
    else
      render :index  
    end
  end
  
  private
  
  def yt_playlist_params
    params.require(:yt_playlist).permit(:url)      
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoutubePlaylistTotal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h2 class="page-title text-center">Youtube Playlist Total Duration Calculator</h2>
  
    <%= form_for(@playlist, url: playlist_total_url, method: :get) do |f| %>
      <div class="form-group">
        <%= f.label :url, "Playlist URL:" %>
        <%= f.text_field :url, size: "75", class: "form-control" %>
      </div>
      
      <%= f.submit "Retrieve", class: "btn btn-primary btn-block btn-lg",
            data: { disable_with: "Retrieving Playlist..." } %>
    <% end %>
    
    
    <% if @playlist.errors.any? %>
      <ul class="error-messages">
        <% @playlist.errors.messages.each do |k, messages| %>
          <% messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
    
  </div>
</div>

app/views/pages/playlist_total.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h2 class="page-title text-center">Playlist Total</h2>
    
    <h3 class="playlist-title text-center">
      <%= link_to @playlist.title, @playlist.url, target: "_blank" %> - 
      Total Duration (<%= @playlist.total_duration %>)
    </h3>
    
    <% if @playlist.videos.any? %>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Thumbnail</th>
            <th>Video Title</th>       
            <th>Video Duration</th>
          </tr>
        </thead>
        <tbody>
          <% @playlist.videos.each do |video| %>
            <tr>
              <td>
                <%= link_to "https://www.youtube.com/watch?v=#{video[:id]}",
                      target: "_blank" do %>
                  <%= image_tag(video[:thumbnail_url]) %>
                <% end %>
              </td>
              <td>
                <%= link_to video[:title] , 
                      "https://www.youtube.com/watch?v=#{video[:id]}",
                      target: "_blank" %>
              </td>
              <td  class="video-duration">
                <%= video[:length] %>
              </td>
            </tr>
          <% end %>
          
          <tr>
            <td colspan="2" class="video-duration">
              <h3>Total Duration:</h3>
            </td>
            <td class="video-duration">
              <strong><%= @playlist.total_duration %></strong>
            </td>
          </tr>
        </tbody>
      </table>
    <% end %>
      
  </div>
</div>